language: node_js
node_js:
  - "node"
branches:
  only:
  - ci
install:
  - npm install node-fetch --loglevel error
script:
  - node main.js
before_deploy:
  - wget https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip -O /tmp/terraform.zip
  - sudo unzip -d /usr/local/bin/ /tmp/terraform.zip
  - terraform fmt $OUTPUT_DIR/
deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  skip-cleanup: true
  keep-history: true
  committer-from-gh: true
  local-dir: $OUTPUT_DIR
  target-branch: master
  on:
    branch: ci
after_deploy:
  - export GIT_TAG="$(git rev-parse --short HEAD)"
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI: version $GIT_TAG"
  - git push --quiet git@github.com:$TRAVIS_REPO_SLUG.git $GIT_TAG
env:
  global:
    - TF_VERSION=0.11.3
    - OUTPUT_DIR=output
    - DIGITALOCEAN_API_BASE=https://api.digitalocean.com/v2/
    - secure: "w3MxFCBFv3FKiDjjfqL4FRjsTXm6wCPZh02KpfXxQEd3NXRSeNYqyFwF2isp+KJi0/6dlT4NY4E6Ht595V7SBpsjn5I9xHZma7F4MoQ4ObPY929inl51wLFhJHLDtRRaXqz3IOBjQsIXVX32TC/OeN/4n0laNtnZZZAM0ACPqFEEM7FMQczMlvvJnTLM9rpybgKh83UW/CexAHyl4zYEiEfs63rZWidTNSH1cG5EkWWpm2pOxNsqEPYWybiXDgc1Hloj7TmcFg4ih5w7NJyyFTGMK0HfE53VVHx3R3R7C9MfAkixZAq4URMI4gBhUt5QBVnf9XtEtJ73sqLLOBb3D55eH83flJxktCn5c14R68VNCp+lHWLZVhmzYiIHZs3O8Q8/PGpdq3bbhYtdnMzv3FE95s4QyW89K2oEq52RaXi/uLun2pl+G5kDECtbbB7pCRg9pQ1ypXBqCdETJza+HUszhQATZW45ouX5UxumxheM+NyxKCouu1zC+r31xOMEqvkwTy/AkHTsZC4PzXNAPHnMSwEXF11wJzONRPGyofCc7jo41s4o5krVVHFiulYTrmOk4OyxLsQh1ppPGlwWDLes9Oz0Wxwy8aR+GbqN7aAYfLtInoglvu+qlLwmJxLGGromEz0g/f1gT7EkFQyF77Hh/k1acarK/CzxajfXB80="
    - secure: "SpaRvTdMJ6axT4NoW1PyJFnXFpCtSbP1FReQDrCmioIAHobGbGjEBWl6NvHQVVOH0CW1W7B+S9SgWq+WuCEpfcLnvqx10oM1QQSuwlxtIqjuD7oz8vEVb/RviF1R1+V7tnUOEB7ONDA6PnJ4GyhoPztHNxu1ZlnZQ+0D7F72XGFH4iPDiwUOOFGLOUNfa9ApAEO/2PP370ueYkn5cWLylROWC2UsbV3f5f6SJ3cWAGINsOOqAy/UILY5BKnPSZu9tM+1uOAnvMVhp+7d6oAg4UZg6JIsX0K3F1zRBZbAh/alZqggrE9mDof2w+j5jsZPd7BvvtRNqYBZS2lLOcdklSku8WyxTAMjq7oDYQ8gTyulAwiBBSt5r/6AeAQyQNH3BkaaRa4NqfUiXD2IIStLRYuAQI7A1i7mY/rgQrh1+pzSrCMM2JG4OQ4s+CN3atffzeS1wFgHh7maxFZOAGtHeLysVIAeRn4OeMAHNcHNI6hM85lV4VLGKzrD+R6UTBKuA7MwjDB67xBGUy1avTGhc51QWngYWbcczZZ1l9rGchPZg95jAKJcteRWwVOudAjMfXSQhy27Ts/wk8ghhSE034uSBpO5tVzvyNgX9X0LAvZhiHFMO7U16u1GAHCl8At9kKHI0EkHdVzYCSwyp/TYF1Lv4qJnGHLbRAfDe8C16Wk="

